services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_USER=artur
      - POSTGRES_PASSWORD=Teste123!@#
      - POSTGRES_DB=template
    ports:
      - '1209:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
